cad:
- CAD/mounts_btt_5160t_plus.step
description: Mounts for BTT 5160T Plus to DIN, 2020 and 1515
images:
- Images/5160T_plus_mount_bottom.jpg
- Images/5160T_plus_mount_top.jpg
- Images/5160T_plus_mounts.jpg
mod_version: 1
printer_compatibility:
- V2.4, VT
stl:
- STL/30mm_fan_shroud_5160T_plus_x2.stl
- STL/40mm_fan_shroud_5160T_plus_x2.stl
- STL/50mm_fan_shroud_5160T_plus_x2.stl
- STL/1515_bracket_5160T_plus.stl
- STL/2020_bracket_5160T_plus.stl
- STL/1515_bracket_5160T_plus.stl
- STL/bracket_pair_5160T_plus_x2.stl
- STL/din_bracket_5160T_plus.stl
- STL/din_bracket_5160T_plus_left.stl
- STL/din_bracket_5160T_plus_right.stl
title: BTT 5160T Plus Mounts
